In [2]:
%load_ext autoreload
%autoreload 2

from keras.layers import merge
from src.models.data import *
from src.models.model import *
#import rasterio.plot as rioplot
import matplotlib

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import rasterio
%matplotlib inline

Using TensorFlow backend.
/Users/kprakash/.pyenv/versions/3.6.5/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/Users/kprakash/.pyenv/versions/3.6.5/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [3]:
model = unet()

/Users/kprakash/Projects/roaddetection/src/models/model.py:60: UserWarning: Update your `Model` call to the Keras 2 API: `Model(inputs=Tensor("in..., outputs=Tensor("co...)`
  model = Model(input=inputs, output=conv10)


__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            (None, 512, 512, 4)  0                                            
__________________________________________________________________________________________________
conv2d_1 (Conv2D)               (None, 512, 512, 64) 2368        input_1[0][0]                    
__________________________________________________________________________________________________
conv2d_2 (Conv2D)               (None, 512, 512, 64) 36928       conv2d_1[0][0]                   
__________________________________________________________________________________________________
max_pooling2d_1 (MaxPooling2D)  (None, 256, 256, 64) 0           conv2d_2[0][0]                   
__________________________________________________________________________________________________
conv2d_3 (

In [4]:
model.load_weights("../../models/unet_membrane_analytic_27_08_14_55.hdf5")

In [9]:
testGene = testGenerator("../../data/test/sat", num_image=1,target_size=(512,512),as_gray=False)

for img, name in testGene:
    results = model.predict(img, batch_size=1)
    saveResult("../../data/test/predict", results, name)

(1, 512, 512, 4) 20180427_020501_103c_3B_0041.tif
[[[[0.4863895 ]
   [0.48542792]
   [0.48238602]
   ...
   [0.47886175]
   [0.47912848]
   [0.4841669 ]]

  [[0.48182213]
   [0.47507122]
   [0.47196203]
   ...
   [0.46829757]
   [0.4674231 ]
   [0.4773514 ]]

  [[0.4792444 ]
   [0.4712234 ]
   [0.46772888]
   ...
   [0.4679763 ]
   [0.46594986]
   [0.4756437 ]]

  ...

  [[0.30002758]
   [0.2465131 ]
   [0.23469551]
   ...
   [0.35848147]
   [0.2995704 ]
   [0.33471498]]

  [[0.32941294]
   [0.2404707 ]
   [0.24713631]
   ...
   [0.30687836]
   [0.28635117]
   [0.35168573]]

  [[0.4197726 ]
   [0.3366119 ]
   [0.30983746]
   ...
   [0.3377963 ]
   [0.34004703]
   [0.35909492]]]]
(1, 512, 512, 4) 20180427_020501_103c_3B_0055.tif
[[[[0.41046497]
   [0.41205552]
   [0.42032397]
   ...
   [0.3314647 ]
   [0.27858716]
   [0.30693093]]

  [[0.43486765]
   [0.47448176]
   [0.49478182]
   ...
   [0.30895954]
   [0.18464828]
   [0.18569297]]

  [[0.43599635]
   [0.467972  ]
   [0.48983583]
   .

/Users/kprakash/.pyenv/versions/3.6.5/Python.framework/Versions/3.6/lib/python3.6/site-packages/skimage/io/_io.py:140: UserWarning: ../../data/test/predict/20180427_020501_103c_3B_0040.tif is a low contrast image
  warn('%s is a low contrast image' % fname)


[[[[0.20223388]
   [0.1912331 ]
   [0.1617823 ]
   ...
   [0.19917752]
   [0.25045064]
   [0.3272165 ]]

  [[0.20586523]
   [0.13517216]
   [0.13101925]
   ...
   [0.13265951]
   [0.16362947]
   [0.23229697]]

  [[0.13726321]
   [0.08035593]
   [0.10551791]
   ...
   [0.06905024]
   [0.07637021]
   [0.1784316 ]]

  ...

  [[0.13469854]
   [0.08097085]
   [0.10770472]
   ...
   [0.46822506]
   [0.39107284]
   [0.3831837 ]]

  [[0.19880642]
   [0.09607718]
   [0.09739079]
   ...
   [0.41143942]
   [0.3861748 ]
   [0.3807179 ]]

  [[0.37483448]
   [0.22433546]
   [0.20991945]
   ...
   [0.36769602]
   [0.35464147]
   [0.3672888 ]]]]
(1, 512, 512, 4) 20180427_020501_103c_3B_0042.tif
[[[[0.30463633]
   [0.30850023]
   [0.27948824]
   ...
   [0.331376  ]
   [0.27515686]
   [0.3062668 ]]

  [[0.35808215]
   [0.30991372]
   [0.26796973]
   ...
   [0.31497148]
   [0.21780534]
   [0.23351812]]

  [[0.28148526]
   [0.22434145]
   [0.20280068]
   ...
   [0.23077194]
   [0.15349156]
   [0.19363305]

/Users/kprakash/.pyenv/versions/3.6.5/Python.framework/Versions/3.6/lib/python3.6/site-packages/skimage/io/_io.py:140: UserWarning: ../../data/test/predict/20170815_005028_0c0b_3B_0042.tif is a low contrast image
  warn('%s is a low contrast image' % fname)


[[[[0.3984151 ]
   [0.41310167]
   [0.41113085]
   ...
   [0.25440446]
   [0.18760498]
   [0.23403066]]

  [[0.42640728]
   [0.4682947 ]
   [0.49807557]
   ...
   [0.2463731 ]
   [0.11385865]
   [0.13058169]]

  [[0.4040217 ]
   [0.46456668]
   [0.49214825]
   ...
   [0.10434084]
   [0.0482115 ]
   [0.08578905]]

  ...

  [[0.18466984]
   [0.10118429]
   [0.08780929]
   ...
   [0.26196986]
   [0.2364164 ]
   [0.31674486]]

  [[0.2622268 ]
   [0.15134607]
   [0.14284015]
   ...
   [0.2124663 ]
   [0.23913415]
   [0.34678876]]

  [[0.3894311 ]
   [0.2923277 ]
   [0.27297696]
   ...
   [0.29437983]
   [0.31383383]
   [0.34776998]]]]
(1, 512, 512, 4) 20170815_005028_0c0b_3B_0043.tif
[[[[0.4863895 ]
   [0.48542792]
   [0.48238602]
   ...
   [0.47886175]
   [0.47912848]
   [0.4841669 ]]

  [[0.48182213]
   [0.47507122]
   [0.47196203]
   ...
   [0.46829757]
   [0.4674231 ]
   [0.4773514 ]]

  [[0.4792444 ]
   [0.4712234 ]
   [0.46772888]
   ...
   [0.4679763 ]
   [0.46594986]
   [0.4756437 ]

/Users/kprakash/.pyenv/versions/3.6.5/Python.framework/Versions/3.6/lib/python3.6/site-packages/skimage/io/_io.py:140: UserWarning: ../../data/test/predict/20170815_005028_0c0b_3B_0043.tif is a low contrast image
  warn('%s is a low contrast image' % fname)


[[[[0.38700646]
   [0.39775833]
   [0.39742482]
   ...
   [0.31509003]
   [0.24402519]
   [0.31091863]]

  [[0.43296802]
   [0.47132573]
   [0.4906123 ]
   ...
   [0.24395195]
   [0.17577814]
   [0.24475121]]

  [[0.43717843]
   [0.47341937]
   [0.49965835]
   ...
   [0.15870443]
   [0.13299729]
   [0.20833088]]

  ...

  [[0.08949053]
   [0.01862837]
   [0.00656976]
   ...
   [0.17284325]
   [0.19815262]
   [0.27676323]]

  [[0.14780062]
   [0.03549071]
   [0.0167889 ]
   ...
   [0.18323806]
   [0.2265337 ]
   [0.32647204]]

  [[0.33750403]
   [0.15344587]
   [0.11232179]
   ...
   [0.29993573]
   [0.30462888]
   [0.34518328]]]]
(1, 512, 512, 4) 20180427_020347_103a_3B_0051.tif
[[[[0.21667321]
   [0.20393158]
   [0.18025883]
   ...
   [0.22761777]
   [0.18514675]
   [0.25512958]]

  [[0.23037857]
   [0.1634778 ]
   [0.1268519 ]
   ...
   [0.13750906]
   [0.10108434]
   [0.16034845]]

  [[0.17516956]
   [0.09675469]
   [0.10147607]
   ...
   [0.05100999]
   [0.04307113]
   [0.1036137 ]

/Users/kprakash/.pyenv/versions/3.6.5/Python.framework/Versions/3.6/lib/python3.6/site-packages/skimage/io/_io.py:140: UserWarning: ../../data/test/predict/20180427_020502_103c_3B_0059.tif is a low contrast image
  warn('%s is a low contrast image' % fname)


[[[[0.30650014]
   [0.33256063]
   [0.33935824]
   ...
   [0.47887683]
   [0.47914445]
   [0.48417148]]

  [[0.35428977]
   [0.43788764]
   [0.48488644]
   ...
   [0.46830976]
   [0.46742672]
   [0.47734696]]

  [[0.32949632]
   [0.4328559 ]
   [0.4748587 ]
   ...
   [0.46798643]
   [0.46594557]
   [0.4756328 ]]

  ...

  [[0.18986546]
   [0.16899303]
   [0.1712804 ]
   ...
   [0.29478264]
   [0.16363606]
   [0.18377602]]

  [[0.27146158]
   [0.19005097]
   [0.2166458 ]
   ...
   [0.19468275]
   [0.14543934]
   [0.1844597 ]]

  [[0.36433113]
   [0.25972268]
   [0.24184638]
   ...
   [0.18871467]
   [0.1589402 ]
   [0.17060043]]]]
(1, 512, 512, 4) 20180427_020347_103a_3B_0055.tif
[[[[0.36422136]
   [0.39176586]
   [0.39086708]
   ...
   [0.38636568]
   [0.37627622]
   [0.3596296 ]]

  [[0.3781104 ]
   [0.42276663]
   [0.4888097 ]
   ...
   [0.4427349 ]
   [0.42804348]
   [0.3665103 ]]

  [[0.39037886]
   [0.44957775]
   [0.48889607]
   ...
   [0.43001285]
   [0.3717071 ]
   [0.35127002]

/Users/kprakash/.pyenv/versions/3.6.5/Python.framework/Versions/3.6/lib/python3.6/site-packages/skimage/io/_io.py:140: UserWarning: ../../data/test/predict/20170815_005028_0c0b_3B_0052.tif is a low contrast image
  warn('%s is a low contrast image' % fname)


[[[[0.42677096]
   [0.43836683]
   [0.4537428 ]
   ...
   [0.26562238]
   [0.20066231]
   [0.25049984]]

  [[0.4674985 ]
   [0.4908983 ]
   [0.49965835]
   ...
   [0.21958295]
   [0.12163797]
   [0.14841782]]

  [[0.47068033]
   [0.4843387 ]
   [0.49965835]
   ...
   [0.07434252]
   [0.05074714]
   [0.09864263]]

  ...

  [[0.44024724]
   [0.40920725]
   [0.4037867 ]
   ...
   [0.26300377]
   [0.21186559]
   [0.27653238]]

  [[0.42273092]
   [0.33457395]
   [0.32733756]
   ...
   [0.21553929]
   [0.18702812]
   [0.29306147]]

  [[0.46033826]
   [0.38323548]
   [0.3626065 ]
   ...
   [0.24161227]
   [0.2410035 ]
   [0.28602314]]]]
(1, 512, 512, 4) 20180427_020502_103c_3B_0058.tif
[[[[0.2533801 ]
   [0.25118485]
   [0.2379562 ]
   ...
   [0.33954778]
   [0.24832115]
   [0.23755756]]

  [[0.29059365]
   [0.22713968]
   [0.24222216]
   ...
   [0.38895506]
   [0.27672142]
   [0.20273954]]

  [[0.21448193]
   [0.16712068]
   [0.20601991]
   ...
   [0.37585887]
   [0.21100494]
   [0.18867387]

/Users/kprakash/.pyenv/versions/3.6.5/Python.framework/Versions/3.6/lib/python3.6/site-packages/skimage/io/_io.py:140: UserWarning: ../../data/test/predict/20180504_094435_0e19_3B_0059.tif is a low contrast image
  warn('%s is a low contrast image' % fname)


[[[[0.3365177 ]
   [0.3205902 ]
   [0.29085878]
   ...
   [0.38169348]
   [0.34272453]
   [0.37598982]]

  [[0.32585973]
   [0.24983768]
   [0.22194518]
   ...
   [0.33578908]
   [0.2963269 ]
   [0.33664405]]

  [[0.2429264 ]
   [0.16352558]
   [0.17441575]
   ...
   [0.2744256 ]
   [0.25758472]
   [0.3121569 ]]

  ...

  [[0.15307638]
   [0.08521322]
   [0.07304656]
   ...
   [0.1369683 ]
   [0.14821228]
   [0.23652166]]

  [[0.19636057]
   [0.07871853]
   [0.06047646]
   ...
   [0.13197272]
   [0.1488412 ]
   [0.23474468]]

  [[0.37237442]
   [0.21041808]
   [0.1717369 ]
   ...
   [0.25584483]
   [0.24939834]
   [0.30277762]]]]
(1, 512, 512, 4) 20180419_074325_0c43_3B_0040.tif
[[[[0.2792431 ]
   [0.2914631 ]
   [0.30236614]
   ...
   [0.16702965]
   [0.12832603]
   [0.19813012]]

  [[0.34607708]
   [0.36393115]
   [0.40467027]
   ...
   [0.09370814]
   [0.05406512]
   [0.09408078]]

  [[0.30807063]
   [0.33467472]
   [0.44067916]
   ...
   [0.03014479]
   [0.02290499]
   [0.06255689]

/Users/kprakash/.pyenv/versions/3.6.5/Python.framework/Versions/3.6/lib/python3.6/site-packages/skimage/io/_io.py:140: UserWarning: ../../data/test/predict/20170815_005028_0c0b_3B_0051.tif is a low contrast image
  warn('%s is a low contrast image' % fname)


[[[[0.3205097 ]
   [0.35334605]
   [0.35678363]
   ...
   [0.2886996 ]
   [0.27601996]
   [0.303983  ]]

  [[0.3422089 ]
   [0.42543197]
   [0.49965835]
   ...
   [0.3426672 ]
   [0.32513353]
   [0.28507215]]

  [[0.28839782]
   [0.42293945]
   [0.4936651 ]
   ...
   [0.3579699 ]
   [0.28357834]
   [0.24777603]]

  ...

  [[0.38522032]
   [0.4297217 ]
   [0.34212235]
   ...
   [0.3262502 ]
   [0.27257636]
   [0.29744637]]

  [[0.39141968]
   [0.35684758]
   [0.3025618 ]
   ...
   [0.31096134]
   [0.29793936]
   [0.31959522]]

  [[0.42588705]
   [0.3202138 ]
   [0.24248543]
   ...
   [0.32234076]
   [0.3210778 ]
   [0.3231094 ]]]]
(1, 512, 512, 4) 20180427_020347_103a_3B_0043.tif
[[[[0.40502217]
   [0.4088538 ]
   [0.4107439 ]
   ...
   [0.3973177 ]
   [0.28459615]
   [0.294967  ]]

  [[0.4060316 ]
   [0.4120875 ]
   [0.47238734]
   ...
   [0.43194452]
   [0.26548752]
   [0.2571087 ]]

  [[0.39076775]
   [0.42094952]
   [0.49965835]
   ...
   [0.4227606 ]
   [0.2136639 ]
   [0.2213785 ]

/Users/kprakash/.pyenv/versions/3.6.5/Python.framework/Versions/3.6/lib/python3.6/site-packages/skimage/io/_io.py:140: UserWarning: ../../data/test/predict/20171013_232848_0c46_3B_0059.tif is a low contrast image
  warn('%s is a low contrast image' % fname)


[[[[0.31624943]
   [0.34620535]
   [0.36547524]
   ...
   [0.17715375]
   [0.14741524]
   [0.2253254 ]]

  [[0.37627935]
   [0.43672708]
   [0.47947648]
   ...
   [0.09043824]
   [0.07016739]
   [0.13153762]]

  [[0.31999972]
   [0.41380906]
   [0.47055718]
   ...
   [0.03334575]
   [0.0375677 ]
   [0.09354558]]

  ...

  [[0.18584843]
   [0.16808824]
   [0.17175013]
   ...
   [0.2246135 ]
   [0.17278157]
   [0.22140285]]

  [[0.21946424]
   [0.1269575 ]
   [0.15251979]
   ...
   [0.16296288]
   [0.1639487 ]
   [0.24845512]]

  [[0.3270099 ]
   [0.20386183]
   [0.18444636]
   ...
   [0.25684804]
   [0.25286514]
   [0.29557705]]]]
(1, 512, 512, 4) 20180419_074324_0c43_3B_0044.tif
[[[[0.30396163]
   [0.36466336]
   [0.3911019 ]
   ...
   [0.2701443 ]
   [0.21431056]
   [0.28864643]]

  [[0.33759022]
   [0.41315052]
   [0.48465878]
   ...
   [0.19927418]
   [0.14161965]
   [0.20477763]]

  [[0.34406766]
   [0.4332923 ]
   [0.48664954]
   ...
   [0.10784481]
   [0.08612188]
   [0.16068505]

/Users/kprakash/.pyenv/versions/3.6.5/Python.framework/Versions/3.6/lib/python3.6/site-packages/skimage/io/_io.py:140: UserWarning: ../../data/test/predict/20171013_232848_0c46_3B_0058.tif is a low contrast image
  warn('%s is a low contrast image' % fname)


[[[[0.24433327]
   [0.24317572]
   [0.24002767]
   ...
   [0.33941922]
   [0.24534826]
   [0.22013451]]

  [[0.30318135]
   [0.33756322]
   [0.4365596 ]
   ...
   [0.41447315]
   [0.3480861 ]
   [0.18406221]]

  [[0.24687791]
   [0.38124427]
   [0.43698063]
   ...
   [0.37990192]
   [0.26773053]
   [0.18324794]]

  ...

  [[0.4815389 ]
   [0.46773958]
   [0.4647539 ]
   ...
   [0.4570802 ]
   [0.45897695]
   [0.47315338]]

  [[0.4829313 ]
   [0.46686605]
   [0.46273786]
   ...
   [0.45674372]
   [0.46010503]
   [0.4721463 ]]

  [[0.4909706 ]
   [0.47934103]
   [0.47576255]
   ...
   [0.47259307]
   [0.4735639 ]
   [0.48048902]]]]
(1, 512, 512, 4) 20180427_020503_103c_3B_0049.tif
[[[[0.4829609 ]
   [0.48161167]
   [0.4718235 ]
   ...
   [0.37630513]
   [0.26070988]
   [0.2699498 ]]

  [[0.480916  ]
   [0.47407869]
   [0.47159302]
   ...
   [0.4097218 ]
   [0.2244099 ]
   [0.20289327]]

  [[0.47676918]
   [0.47366372]
   [0.48611936]
   ...
   [0.22431059]
   [0.11236266]
   [0.13269415]

/Users/kprakash/.pyenv/versions/3.6.5/Python.framework/Versions/3.6/lib/python3.6/site-packages/skimage/io/_io.py:140: UserWarning: ../../data/test/predict/20170920_015736_0f28_3B_0059.tif is a low contrast image
  warn('%s is a low contrast image' % fname)


[[[[0.26753786]
   [0.2801554 ]
   [0.2874209 ]
   ...
   [0.40513965]
   [0.36972952]
   [0.35993093]]

  [[0.32257733]
   [0.40409806]
   [0.47080353]
   ...
   [0.47221294]
   [0.4293161 ]
   [0.33652586]]

  [[0.3072587 ]
   [0.40856418]
   [0.44891134]
   ...
   [0.43569002]
   [0.3151279 ]
   [0.26095718]]

  ...

  [[0.4815389 ]
   [0.46773958]
   [0.4647539 ]
   ...
   [0.40545133]
   [0.30405453]
   [0.27101701]]

  [[0.4829313 ]
   [0.46686605]
   [0.46273786]
   ...
   [0.3732438 ]
   [0.29470694]
   [0.2714131 ]]

  [[0.4909706 ]
   [0.47934103]
   [0.47576255]
   ...
   [0.2957791 ]
   [0.2467716 ]
   [0.2518504 ]]]]
(1, 512, 512, 4) 20180606_020625_0f1b_3B_0057.tif
[[[[0.26034138]
   [0.31382617]
   [0.30806258]
   ...
   [0.33637565]
   [0.2817    ]
   [0.28917187]]

  [[0.23939922]
   [0.31329674]
   [0.46515432]
   ...
   [0.3964231 ]
   [0.28547186]
   [0.23497517]]

  [[0.26764014]
   [0.39260572]
   [0.47634917]
   ...
   [0.30884668]
   [0.18340191]
   [0.1950837 ]

/Users/kprakash/.pyenv/versions/3.6.5/Python.framework/Versions/3.6/lib/python3.6/site-packages/skimage/io/_io.py:140: UserWarning: ../../data/test/predict/20180724_094554_0e19_3B_0058.tif is a low contrast image
  warn('%s is a low contrast image' % fname)


[[[[0.48629257]
   [0.4854146 ]
   [0.4823513 ]
   ...
   [0.47886175]
   [0.47912848]
   [0.4841669 ]]

  [[0.48179445]
   [0.47511986]
   [0.47201803]
   ...
   [0.46829757]
   [0.4674231 ]
   [0.4773514 ]]

  [[0.47919756]
   [0.4712078 ]
   [0.46774083]
   ...
   [0.4679763 ]
   [0.46594986]
   [0.4756437 ]]

  ...

  [[0.22162436]
   [0.3274579 ]
   [0.35071948]
   ...
   [0.0517827 ]
   [0.06536459]
   [0.15953702]]

  [[0.30478743]
   [0.31923935]
   [0.34718892]
   ...
   [0.08459192]
   [0.10093118]
   [0.21246934]]

  [[0.36221236]
   [0.2810224 ]
   [0.23959339]
   ...
   [0.23537636]
   [0.21156472]
   [0.2660537 ]]]]
(1, 512, 512, 4) 20180427_020346_103a_3B_0056.tif
[[[[0.31693906]
   [0.32778478]
   [0.30949354]
   ...
   [0.13288341]
   [0.09780343]
   [0.16663055]]

  [[0.37357205]
   [0.34641752]
   [0.3525621 ]
   ...
   [0.06407689]
   [0.03636761]
   [0.0744115 ]]

  [[0.30642223]
   [0.28541133]
   [0.31671485]
   ...
   [0.02330506]
   [0.01821484]
   [0.04972937]

/Users/kprakash/.pyenv/versions/3.6.5/Python.framework/Versions/3.6/lib/python3.6/site-packages/skimage/io/_io.py:140: UserWarning: ../../data/test/predict/20180427_020504_103c_3B_0040.tif is a low contrast image
  warn('%s is a low contrast image' % fname)


[[[[0.30083874]
   [0.3370212 ]
   [0.3641671 ]
   ...
   [0.2937042 ]
   [0.222167  ]
   [0.22978257]]

  [[0.30457103]
   [0.37413514]
   [0.49176124]
   ...
   [0.3381219 ]
   [0.20676565]
   [0.16494934]]

  [[0.25048786]
   [0.36366576]
   [0.4815712 ]
   ...
   [0.27194136]
   [0.14480746]
   [0.14124253]]

  ...

  [[0.45397717]
   [0.49965835]
   [0.49965835]
   ...
   [0.24879284]
   [0.14539129]
   [0.17441939]]

  [[0.4426294 ]
   [0.4541497 ]
   [0.40547672]
   ...
   [0.24227832]
   [0.19028835]
   [0.22301397]]

  [[0.43446836]
   [0.362305  ]
   [0.30713406]
   ...
   [0.25307453]
   [0.22250026]
   [0.21390867]]]]
(1, 512, 512, 4) 20180310_020202_1040_3B_0051.tif
[[[[0.4863895 ]
   [0.48542792]
   [0.48238602]
   ...
   [0.47886175]
   [0.47912848]
   [0.4841669 ]]

  [[0.48182213]
   [0.47507122]
   [0.47196203]
   ...
   [0.46829757]
   [0.4674231 ]
   [0.4773514 ]]

  [[0.4792444 ]
   [0.4712234 ]
   [0.46772888]
   ...
   [0.4679763 ]
   [0.46594986]
   [0.4756437 ]

/Users/kprakash/.pyenv/versions/3.6.5/Python.framework/Versions/3.6/lib/python3.6/site-packages/skimage/io/_io.py:140: UserWarning: ../../data/test/predict/20171013_232848_0c46_3B_0049.tif is a low contrast image
  warn('%s is a low contrast image' % fname)


[[[[0.26216814]
   [0.29794315]
   [0.35771286]
   ...
   [0.34581777]
   [0.30939636]
   [0.30585742]]

  [[0.3847893 ]
   [0.4436075 ]
   [0.4953495 ]
   ...
   [0.46682265]
   [0.40569314]
   [0.29874066]]

  [[0.35451472]
   [0.4123377 ]
   [0.4718065 ]
   ...
   [0.4335316 ]
   [0.32068753]
   [0.21295702]]

  ...

  [[0.12884974]
   [0.09862044]
   [0.1302525 ]
   ...
   [0.11145329]
   [0.09706624]
   [0.15242517]]

  [[0.17258386]
   [0.09137676]
   [0.08935674]
   ...
   [0.06576052]
   [0.08653001]
   [0.18267491]]

  [[0.29573628]
   [0.15783961]
   [0.12374802]
   ...
   [0.14323758]
   [0.16323902]
   [0.19484958]]]]
(1, 512, 512, 4) 20170920_015736_0f28_3B_0057.tif
[[[[0.3247894 ]
   [0.33157805]
   [0.37876293]
   ...
   [0.34188563]
   [0.23099624]
   [0.19917768]]

  [[0.42593047]
   [0.47203565]
   [0.49965835]
   ...
   [0.42020088]
   [0.2848649 ]
   [0.14990668]]

  [[0.4257839 ]
   [0.4481172 ]
   [0.48527426]
   ...
   [0.34716007]
   [0.1707455 ]
   [0.13256678]

/Users/kprakash/.pyenv/versions/3.6.5/Python.framework/Versions/3.6/lib/python3.6/site-packages/skimage/io/_io.py:140: UserWarning: ../../data/test/predict/20171013_232848_0c46_3B_0050.tif is a low contrast image
  warn('%s is a low contrast image' % fname)


[[[[0.31079888]
   [0.34672704]
   [0.35932246]
   ...
   [0.2639972 ]
   [0.20279546]
   [0.21466067]]

  [[0.337945  ]
   [0.4149067 ]
   [0.49346378]
   ...
   [0.31507918]
   [0.1755617 ]
   [0.15121576]]

  [[0.3090671 ]
   [0.43354803]
   [0.49382097]
   ...
   [0.25773177]
   [0.11872444]
   [0.136258  ]]

  ...

  [[0.48149115]
   [0.46208054]
   [0.46073654]
   ...
   [0.37918267]
   [0.23382293]
   [0.2606809 ]]

  [[0.48308685]
   [0.46211383]
   [0.4607673 ]
   ...
   [0.33010826]
   [0.2575636 ]
   [0.26872054]]

  [[0.49192038]
   [0.47814733]
   [0.474925  ]
   ...
   [0.2943412 ]
   [0.25964963]
   [0.24840927]]]]
(1, 512, 512, 4) 20180419_074324_0c43_3B_0059.tif
[[[[0.3755045 ]
   [0.38337842]
   [0.37406886]
   ...
   [0.40016046]
   [0.34218594]
   [0.3676064 ]]

  [[0.41758135]
   [0.46666923]
   [0.4927879 ]
   ...
   [0.3813346 ]
   [0.28506047]
   [0.30420464]]

  [[0.41932315]
   [0.45687914]
   [0.48880094]
   ...
   [0.3281059 ]
   [0.20862763]
   [0.25719494]

/Users/kprakash/.pyenv/versions/3.6.5/Python.framework/Versions/3.6/lib/python3.6/site-packages/skimage/io/_io.py:140: UserWarning: ../../data/test/predict/20170920_015736_0f28_3B_0040.tif is a low contrast image
  warn('%s is a low contrast image' % fname)


[[[[0.22311944]
   [0.27870595]
   [0.29817882]
   ...
   [0.35150504]
   [0.32296246]
   [0.31747147]]

  [[0.3431389 ]
   [0.4141066 ]
   [0.46351433]
   ...
   [0.40076977]
   [0.33125493]
   [0.29082662]]

  [[0.24618477]
   [0.29413512]
   [0.45115048]
   ...
   [0.41604957]
   [0.29476753]
   [0.28970677]]

  ...

  [[0.18728158]
   [0.16490687]
   [0.2648635 ]
   ...
   [0.04634868]
   [0.04867484]
   [0.13042544]]

  [[0.25269064]
   [0.18688856]
   [0.21269348]
   ...
   [0.06369668]
   [0.07533832]
   [0.16923144]]

  [[0.3725243 ]
   [0.28298104]
   [0.25036317]
   ...
   [0.1685592 ]
   [0.15437049]
   [0.20241226]]]]
(1, 512, 512, 4) 20171013_232848_0c46_3B_0053.tif
[[[[0.28940108]
   [0.29859257]
   [0.31744814]
   ...
   [0.28543115]
   [0.21490991]
   [0.19799358]]

  [[0.35377195]
   [0.4387579 ]
   [0.48846677]
   ...
   [0.40986723]
   [0.27182645]
   [0.16156667]]

  [[0.28637668]
   [0.399918  ]
   [0.46128753]
   ...
   [0.31232572]
   [0.15918478]
   [0.13943522]

/Users/kprakash/.pyenv/versions/3.6.5/Python.framework/Versions/3.6/lib/python3.6/site-packages/skimage/io/_io.py:140: UserWarning: ../../data/test/predict/20180427_020503_103c_3B_0040.tif is a low contrast image
  warn('%s is a low contrast image' % fname)


[[[[0.23243846]
   [0.2537344 ]
   [0.26571706]
   ...
   [0.3387102 ]
   [0.3091924 ]
   [0.32369828]]

  [[0.33128467]
   [0.41750887]
   [0.47200677]
   ...
   [0.41317934]
   [0.35713208]
   [0.28817284]]

  [[0.25467995]
   [0.38334695]
   [0.45367977]
   ...
   [0.42224452]
   [0.30810636]
   [0.26286817]]

  ...

  [[0.4815389 ]
   [0.46773958]
   [0.4647539 ]
   ...
   [0.4570802 ]
   [0.45897695]
   [0.47315338]]

  [[0.4829313 ]
   [0.46686605]
   [0.46273786]
   ...
   [0.45674372]
   [0.46010503]
   [0.4721463 ]]

  [[0.4909706 ]
   [0.47934103]
   [0.47576255]
   ...
   [0.47259307]
   [0.4735639 ]
   [0.48048902]]]]
(1, 512, 512, 4) 20180419_074323_0c43_3B_0054.tif
[[[[0.37534264]
   [0.38091952]
   [0.37208837]
   ...
   [0.40494436]
   [0.3660654 ]
   [0.370988  ]]

  [[0.42523357]
   [0.45644668]
   [0.47333226]
   ...
   [0.43488887]
   [0.34935084]
   [0.34479487]]

  [[0.38602263]
   [0.43256462]
   [0.48542815]
   ...
   [0.40122077]
   [0.29398215]
   [0.33595726]

/Users/kprakash/.pyenv/versions/3.6.5/Python.framework/Versions/3.6/lib/python3.6/site-packages/skimage/io/_io.py:140: UserWarning: ../../data/test/predict/20180606_020625_0f1b_3B_0059.tif is a low contrast image
  warn('%s is a low contrast image' % fname)


[[[[0.24462438]
   [0.25066233]
   [0.24304873]
   ...
   [0.30466822]
   [0.30088645]
   [0.27849337]]

  [[0.30446225]
   [0.31864065]
   [0.3520448 ]
   ...
   [0.43588498]
   [0.42133644]
   [0.298973  ]]

  [[0.23164538]
   [0.24745974]
   [0.38461208]
   ...
   [0.40463492]
   [0.34261888]
   [0.23743603]]

  ...

  [[0.2898303 ]
   [0.31776354]
   [0.38089085]
   ...
   [0.31490284]
   [0.27643293]
   [0.29778945]]

  [[0.34055075]
   [0.3271429 ]
   [0.32714003]
   ...
   [0.22373189]
   [0.2334895 ]
   [0.29803684]]

  [[0.4051849 ]
   [0.32760617]
   [0.28098887]
   ...
   [0.25956303]
   [0.26245314]
   [0.29539034]]]]
(1, 512, 512, 4) 20180427_020503_103c_3B_0041.tif
[[[[0.4863895 ]
   [0.48542792]
   [0.48238602]
   ...
   [0.47886175]
   [0.47912848]
   [0.4841669 ]]

  [[0.48182213]
   [0.47507122]
   [0.47196203]
   ...
   [0.46829757]
   [0.4674231 ]
   [0.4773514 ]]

  [[0.4792444 ]
   [0.4712234 ]
   [0.46772888]
   ...
   [0.4679763 ]
   [0.46594986]
   [0.4756437 ]

/Users/kprakash/.pyenv/versions/3.6.5/Python.framework/Versions/3.6/lib/python3.6/site-packages/skimage/io/_io.py:140: UserWarning: ../../data/test/predict/20171013_232848_0c46_3B_0041.tif is a low contrast image
  warn('%s is a low contrast image' % fname)


[[[[0.23257564]
   [0.2486642 ]
   [0.24159373]
   ...
   [0.30373567]
   [0.20051238]
   [0.23957579]]

  [[0.30947673]
   [0.29978007]
   [0.32229608]
   ...
   [0.30565757]
   [0.16998297]
   [0.16010356]]

  [[0.21645507]
   [0.20570296]
   [0.3088876 ]
   ...
   [0.1913709 ]
   [0.10477402]
   [0.13658854]]

  ...

  [[0.08201507]
   [0.02958367]
   [0.02589933]
   ...
   [0.08504011]
   [0.06733526]
   [0.13542102]]

  [[0.1407175 ]
   [0.04177741]
   [0.04190771]
   ...
   [0.07582804]
   [0.07126729]
   [0.15453276]]

  [[0.3049447 ]
   [0.14224267]
   [0.12059858]
   ...
   [0.1535857 ]
   [0.14534105]
   [0.1809401 ]]]]
(1, 512, 512, 4) 20180427_020503_103c_3B_0052.tif
[[[[0.39406487]
   [0.4453429 ]
   [0.42992717]
   ...
   [0.1567376 ]
   [0.09825093]
   [0.164204  ]]

  [[0.47658587]
   [0.49441403]
   [0.49965835]
   ...
   [0.11100324]
   [0.04521708]
   [0.07447482]]

  [[0.4911088 ]
   [0.49562255]
   [0.49965835]
   ...
   [0.04113627]
   [0.02038404]
   [0.04867917]

/Users/kprakash/.pyenv/versions/3.6.5/Python.framework/Versions/3.6/lib/python3.6/site-packages/skimage/io/_io.py:140: UserWarning: ../../data/test/predict/20170815_005030_0c0b_3B_0052.tif is a low contrast image
  warn('%s is a low contrast image' % fname)


[[[[0.3212237 ]
   [0.33817482]
   [0.339181  ]
   ...
   [0.2559487 ]
   [0.2117125 ]
   [0.2079434 ]]

  [[0.33544168]
   [0.40188783]
   [0.4872818 ]
   ...
   [0.36897907]
   [0.30466506]
   [0.22023508]]

  [[0.2961743 ]
   [0.4132419 ]
   [0.47768754]
   ...
   [0.31684035]
   [0.21354987]
   [0.19899061]]

  ...

  [[0.38455325]
   [0.44518787]
   [0.45695326]
   ...
   [0.14968587]
   [0.09348942]
   [0.14463697]]

  [[0.3892115 ]
   [0.35824037]
   [0.36001405]
   ...
   [0.14811313]
   [0.12524168]
   [0.18891235]]

  [[0.40616286]
   [0.34462357]
   [0.32331172]
   ...
   [0.20888738]
   [0.1995692 ]
   [0.19064666]]]]
(1, 512, 512, 4) 20170815_005030_0c0b_3B_0050.tif
[[[[0.2582223 ]
   [0.29098776]
   [0.29900077]
   ...
   [0.2954004 ]
   [0.2534942 ]
   [0.24401832]]

  [[0.3210684 ]
   [0.37777084]
   [0.45982823]
   ...
   [0.42191777]
   [0.28336754]
   [0.20067476]]

  [[0.25946292]
   [0.38475475]
   [0.4385116 ]
   ...
   [0.36801407]
   [0.19910704]
   [0.17421633]

/Users/kprakash/.pyenv/versions/3.6.5/Python.framework/Versions/3.6/lib/python3.6/site-packages/skimage/io/_io.py:140: UserWarning: ../../data/test/predict/20180427_020502_103c_3B_0040.tif is a low contrast image
  warn('%s is a low contrast image' % fname)


[[[[0.3686074 ]
   [0.339853  ]
   [0.33997786]
   ...
   [0.3408544 ]
   [0.32915196]
   [0.33367908]]

  [[0.37388664]
   [0.425211  ]
   [0.49965835]
   ...
   [0.40687403]
   [0.3902511 ]
   [0.33480388]]

  [[0.3643206 ]
   [0.4495423 ]
   [0.49016047]
   ...
   [0.44201553]
   [0.32216436]
   [0.2758688 ]]

  ...

  [[0.12559368]
   [0.11166194]
   [0.20688576]
   ...
   [0.05850428]
   [0.0434278 ]
   [0.13055483]]

  [[0.18536513]
   [0.12471285]
   [0.16887847]
   ...
   [0.0765476 ]
   [0.06654039]
   [0.15227342]]

  [[0.30196065]
   [0.1881701 ]
   [0.16878834]
   ...
   [0.18587278]
   [0.15596199]
   [0.20144229]]]]
(1, 512, 512, 4) 20180504_094435_0e19_3B_0043.tif
[[[[0.22705624]
   [0.20285273]
   [0.19551256]
   ...
   [0.4356778 ]
   [0.39158556]
   [0.4013463 ]]

  [[0.26376945]
   [0.20835915]
   [0.19249855]
   ...
   [0.44628146]
   [0.3829544 ]
   [0.36856055]]

  [[0.19026302]
   [0.11122494]
   [0.1398156 ]
   ...
   [0.4148372 ]
   [0.34244677]
   [0.35169092]

/Users/kprakash/.pyenv/versions/3.6.5/Python.framework/Versions/3.6/lib/python3.6/site-packages/skimage/io/_io.py:140: UserWarning: ../../data/test/predict/20170815_005030_0c0b_3B_0051.tif is a low contrast image
  warn('%s is a low contrast image' % fname)


[[[[0.29511577]
   [0.33134332]
   [0.34085932]
   ...
   [0.31221882]
   [0.2500791 ]
   [0.2528089 ]]

  [[0.2864125 ]
   [0.3477513 ]
   [0.4945817 ]
   ...
   [0.36677033]
   [0.2967698 ]
   [0.23291834]]

  [[0.21487735]
   [0.31568626]
   [0.47256115]
   ...
   [0.31738177]
   [0.20873913]
   [0.19793436]]

  ...

  [[0.12212309]
   [0.10875984]
   [0.16519426]
   ...
   [0.36377695]
   [0.19515131]
   [0.21614684]]

  [[0.19318633]
   [0.13264042]
   [0.17814499]
   ...
   [0.29759732]
   [0.1991375 ]
   [0.23002891]]

  [[0.31598568]
   [0.19571349]
   [0.1764852 ]
   ...
   [0.23762208]
   [0.20549805]
   [0.20701134]]]]
(1, 512, 512, 4) 20170815_005030_0c0b_3B_0041.tif
[[[[0.3177399 ]
   [0.37300068]
   [0.376578  ]
   ...
   [0.39328736]
   [0.3262296 ]
   [0.3038164 ]]

  [[0.345166  ]
   [0.41615567]
   [0.49533764]
   ...
   [0.44000536]
   [0.4377331 ]
   [0.3122315 ]]

  [[0.23938304]
   [0.3314907 ]
   [0.4642085 ]
   ...
   [0.41196033]
   [0.37121943]
   [0.27682066]

/Users/kprakash/.pyenv/versions/3.6.5/Python.framework/Versions/3.6/lib/python3.6/site-packages/skimage/io/_io.py:140: UserWarning: ../../data/test/predict/20170815_005030_0c0b_3B_0043.tif is a low contrast image
  warn('%s is a low contrast image' % fname)


[[[[0.36957216]
   [0.43101767]
   [0.4368463 ]
   ...
   [0.3106437 ]
   [0.30557513]
   [0.34725425]]

  [[0.4356617 ]
   [0.4844758 ]
   [0.49965835]
   ...
   [0.3138498 ]
   [0.3072365 ]
   [0.33196217]]

  [[0.42751873]
   [0.4953206 ]
   [0.49965835]
   ...
   [0.31307825]
   [0.29298738]
   [0.34141225]]

  ...

  [[0.4815389 ]
   [0.46773958]
   [0.4647539 ]
   ...
   [0.4570802 ]
   [0.45897695]
   [0.47315338]]

  [[0.4829313 ]
   [0.46686605]
   [0.46273786]
   ...
   [0.45674372]
   [0.46010503]
   [0.4721463 ]]

  [[0.4909706 ]
   [0.47934103]
   [0.47576255]
   ...
   [0.47259307]
   [0.4735639 ]
   [0.48048902]]]]


In [ ]:
# np.unique(results[7])

In [ ]:
results.dtype

In [ ]:
results[0].shape

In [ ]:
r=results[0].reshape((512,512))
r.shape


In [ ]:
q = p[0].reshape((512,512))

plt.imshow(q, cmap="gray")